#!/bin/zsh
if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object (Add the first sha for your repo)
  against=SHA
fi

# The special marker tag to mark things which we still need to change
marker="#BOOM#"

# Redirect output to stderr.
exec 1>&2

if test $(git diff --cached -z $against | grep $marker | wc -c) != 0 
then
    cat <<\EOF
    Error: Still has invalid debug markers in code:
EOF
    echo "\tExecute the following command =>" git diff --cached -z $(echo $against) -G '"'$(echo $marker)'"'
    OUTPUT=$(git diff --cached -z $against -G "$marker")
    echo $OUTPUT
    exit 1
fi
